# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "staticise"
  s.version = "0.6.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Melvin Sembrano"]
  s.date = "2013-06-14"
  s.description = "Static site generator using Haml and Coffescript"
  s.email = "melvinsembrano@gmail.com"
  s.executables = ["staticise"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/css/st.sass",
    "app/css/test-1.less",
    "app/css/test.sass",
    "app/js/main.coffee",
    "app/js/plugins/a.coffee",
    "app/layouts/app.haml",
    "app/layouts/app.html",
    "app/pages/_footer.haml",
    "app/pages/_footer.html",
    "app/pages/cat/index.haml",
    "app/pages/dog/index.haml",
    "app/pages/help.html",
    "app/pages/index.haml",
    "app/pages/lion/index.haml",
    "app/pages/t.haml",
    "bin/staticise",
    "config.yml",
    "lib/guard/staticise.rb",
    "lib/guard/staticise/notifier.rb",
    "lib/staticise.rb",
    "lib/staticise/cli.rb",
    "lib/staticise/renderer.rb",
    "lib/staticise/watcher.rb",
    "public/cat/index.html",
    "public/css/test-1.css",
    "public/css/test.css",
    "public/dog/index.html",
    "public/help.html",
    "public/index.html",
    "public/js/app.js",
    "public/js/main.js",
    "public/js/plugins/a.js",
    "public/lion/index.html",
    "public/t.html",
    "staticise.gemspec",
    "test/helper.rb",
    "test/test_staticise.rb"
  ]
  s.homepage = "http://github.com/melvinsembrano/staticise"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Static site generator using Haml and Coffescript"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<sass>, [">= 0"])
      s.add_runtime_dependency(%q<coffee-script>, [">= 0"])
      s.add_runtime_dependency(%q<guard>, [">= 0"])
      s.add_runtime_dependency(%q<guard-coffeescript>, [">= 0"])
      s.add_runtime_dependency(%q<guard-sass>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<sass>, [">= 0"])
      s.add_dependency(%q<coffee-script>, [">= 0"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<guard-coffeescript>, [">= 0"])
      s.add_dependency(%q<guard-sass>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<sass>, [">= 0"])
    s.add_dependency(%q<coffee-script>, [">= 0"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<guard-coffeescript>, [">= 0"])
    s.add_dependency(%q<guard-sass>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

